# Cleaning of geoapify json response

In [2]:
import json
from pathlib import Path
import pandas as pd

In [3]:
RAW_FILE = "../raw/venues_raw.json"
CLEAN_JSON = "../cleaned/venues_cleaned.json"
CLEAN_CSV = "../cleaned/venues_cleaned.csv"

with open(RAW_FILE, "r", encoding="utf-8") as file:
    raw_data = json.load(file)

print(f"Raw records loaded: {len(raw_data)}")

df = pd.json_normalize(raw_data)

Raw records loaded: 400

In [4]:
print(df.shape)
print(df.columns)
print(df.info())

(400, 392)
Index(['type', 'properties.name', 'properties.country',
       'properties.country_code', 'properties.state', 'properties.city',
       'properties.postcode', 'properties.suburb', 'properties.quarter',
       'properties.street',
       ...
       'properties.datasource.raw.min_height',
       'properties.datasource.raw.payment:cards',
       'properties.datasource.raw.roof:material',
       'properties.payment_options.cards', 'properties.datasource.raw.leisure',
       'properties.datasource.raw.max_age', 'properties.restrictions.max_age',
       'properties.datasource.raw.barrier',
       'properties.datasource.raw.fence_type',
       'properties.datasource.raw.surface'],
      dtype='str', length=392)
<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Columns: 392 entries, type to properties.datasource.raw.surface
dtypes: float64(27), int64(2), object(41), str(322)
memory usage: 1.2+ MB
None

### The below code is to save the starting count

In [5]:
len(df)

400

In [17]:
print(raw_data)

[{'type': 'Feature', 'properties': {'name': 'Caffè Nero', 'country': 'United Kingdom', 'country_code': 'gb', 'state': 'England', 'city': 'City of Westminster', 'postcode': 'WC2N 5DS', 'suburb': 'Covent Garden', 'quarter': 'Westminster', 'street': 'Trafalgar Square', 'housenumber': '60-61', 'iso3166_2': 'GB-ENG', 'iso3166_2_sublevel': 'GB-WSM', 'lon': -0.1283651, 'lat': 51.5072772, 'state_code': 'ENG', 'formatted': 'Caffè Nero, 60-61 Trafalgar Square, London, WC2N 5DS, United Kingdom', 'address_line1': 'Caffè Nero', 'address_line2': '60-61 Trafalgar Square, London, WC2N 5DS, United Kingdom', 'categories': ['catering', 'catering.cafe', 'catering.cafe.coffee', 'catering.cafe.coffee_shop', 'vegan', 'vegetarian'], 'details': ['details', 'details.catering', 'details.facilities', 'details.payment'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'lat': 51.5072772, 'lon': -0.1283651, 'city': 'London', 'name': 'Caffè Nero', 'brand': 'Caffè Nero', 'level': 0, 'osm_id': 559520875, 'street': 'Trafalgar Square', 'amenity': 'cafe', 'cuisine': 'coffee_shop', 'fhrs:id': 411203, 'name:en': 'Caffè Nero', 'name:ja': 'カフェ・ネロ', 'smoking': 'no', 'website': 'https://www.caffenero.com/uk/stores/trafalgar-sq', 'osm_type': 'n', 'postcode': 'WC2N 5DS', 'takeaway': 'yes', 'check_date': '2026-01-07', 'diet:vegan': 'yes', 'wheelchair': 'no', 'housenumber': '60-61', 'payment:cash': 'yes', 'opening_hours': 'Mo-Fr 06:30-21:00; Sa 07:00-21:00; Su 07:30-20:00', 'addr:housename': 'Serck House', 'brand:wikidata': 'Q675808', 'indoor_seating': 'yes', 'brand:wikipedia': 'en:Caffè Nero', 'diet:vegetarian': 'yes', 'outdoor_seating': 'no', 'air_conditioning': 'yes', 'check_date:smoking': '2024-10-02', 'payment:contactless': 'yes', 'payment:credit_cards': 'yes', 'check_date:diet:vegan': '2024-10-02', 'check_date:opening_hours': '2024-08-22', 'payment:american_express': 'yes', 'check_date:diet:vegetarian': '2024-10-02'}}, 'website': 'https://www.caffenero.com/uk/stores/trafalgar-sq', 'opening_hours': 'Mo-Fr 06:30-21:00; Sa 07:00-21:00; Su 07:30-20:00', 'brand': 'Caffè Nero', 'brand_details': {'wikidata': 'Q675808', 'wikipedia': 'en:Caffè Nero'}, 'name_international': {'en': 'Caffè Nero', 'ja': 'カフェ・ネロ'}, 'facilities': {'wheelchair': False, 'smoking': False, 'air_conditioning': True, 'outdoor_seating': False, 'takeaway': True}, 'payment_options': {'cash': True, 'contactless': True, 'credit_cards': True, 'american_express': True}, 'catering': {'cuisine': 'coffee_shop', 'diet': {'vegan': True, 'vegetarian': True}}, 'distance': 54, 'place_id': '5184503981446ec0bf59d3009475eec04940f00103f9016b9c59210000000092030b43616666c3a8204e65726f'}, 'geometry': {'type': 'Point', 'coordinates': [-0.1283651, 51.5072772]}}, {'type': 'Feature', 'properties': {'name': 'Caffe Concerto', 'country': 'United Kingdom', 'country_code': 'gb', 'state': 'England', 'city': 'City of Westminster', 'postcode': 'WC2N 5BW', 'suburb': 'Covent Garden', 'quarter': 'Westminster', 'street': 'Northumberland Avenue', 'housenumber': '4-5', 'iso3166_2': 'GB-ENG', 'iso3166_2_sublevel': 'GB-WSM', 'lon': -0.1266925, 'lat': 51.5071158, 'state_code': 'ENG', 'formatted': 'Caffe Concerto, 4-5 Northumberland Avenue, London, WC2N 5BW, United Kingdom', 'address_line1': 'Caffe Concerto', 'address_line2': '4-5 Northumberland Avenue, London, WC2N 5BW, United Kingdom', 'categories': ['catering', 'catering.cafe', 'wheelchair', 'wheelchair.limited'], 'details': ['details', 'details.contact', 'details.facilities'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'lat': 51.50710053752334, 'lon': -0.1267043397547849, 'city': 'London', 'name': 'Caffe Concerto', 'email': 'trafalgersquare@caffeconcerto.co.uk', 'level': 0, 'phone': '+44 20 7494 6851', 'osm_id': 550944275, 'street': 'Northumberland Avenue', 'amenity': 'cafe', 'fhrs:id': 727063, 'website': 'https://www.caffeconcerto.co.uk/', 'osm_type': 'w', 'postcode': 'WC2N 5BW', 'breakfast': '07:00-11:30', 'wheelchair': 'limited', 'housenumber': '4-5', 'opening_hours': '07:00-23:00'}}, 'website': 'https://www.caffeconcerto.co.uk/', 'opening_hours': '07:00-23:00', 'contact': {'phone': '+44 20 7494 6851', 'email': 'trafalgersquare@caffeconcerto.co.uk'}, 'facilities': {'wheelchair': True, 'wheelchair_details': {'condition': 'limited'}}, 'distance': 63, 'place_id': '519008c109d937c0bf593039a0abe8c04940f00102f90113bed6200000000092030e436166666520436f6e636572746f'}, 'geometry': {'type': 'Point', 'coordinates': [-0.1267043397547849, 51.50710053752334]}}, {'type': 'Feature', 'properties': {'name': 'Costa', 'country': 'United Kingdom', 'country_code': 'gb', 'state': 'England', 'city': 'City of Westminster', 'postcode': 'WC2N 5NJ', 'suburb': 'Covent Garden', 'quarter': 'Westminster', 'street': 'Strand', 'housenumber': '1', 'iso3166_2': 'GB-ENG', 'iso3166_2_sublevel': 'GB-WSM', 'lon': -0.1267675, 'lat': 51.5075005, 'state_code': 'ENG', 'formatted': 'Costa, 1 Strand, London, WC2N 5NJ, United Kingdom', 'address_line1': 'Costa', 'address_line2': '1 Strand, London, WC2N 5NJ, United Kingdom', 'categories': ['catering', 'catering.cafe', 'catering.cafe.coffee', 'catering.cafe.coffee_shop', 'wheelchair', 'wheelchair.yes'], 'details': ['details', 'details.catering', 'details.facilities'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'lat': 51.5075005, 'lon': -0.1267675, 'city': 'London', 'name': 'Costa', 'brand': 'Costa', 'osm_id': 588034827, 'street': 'Strand', 'amenity': 'cafe', 'cuisine': 'coffee_shop', 'name:en': 'Costa', 'name:ja': 'コスタ', 'toilets': 'yes', 'osm_type': 'n', 'takeaway': 'yes', '_inherited': '', 'wheelchair': 'yes', 'housenumber': 1, 'brand:wikidata': 'Q608845', 'brand:wikipedia': 'en:Costa Coffee', 'toilets:wheelchair': 'yes'}}, 'brand': 'Costa', 'brand_details': {'wikidata': 'Q608845', 'wikipedia': 'en:Costa Coffee'}, 'name_international': {'en': 'Costa', 'ja': 'コスタ'}, 'facilities': {'wheelchair': True, 'toilets': True, 'takeaway': True}, 'catering': {'cuisine': 'coffee_shop'}, 'distance': 67, 'place_id': '510b0c59ddea39c0bf59111ac1c6f5c04940f00103f9010bb30c2300000000920305436f737461'}, 'geometry': {'type': 'Point', 'coordinates': [-0.1267675, 51.5075005]}}, {'type': 'Feature', 'properties': {'name': 'The Grand Caffè', 'country': 'United Kingdom', 'country_code': 'gb', 'state': 'England', 'city': 'City of Westminster', 'postcode': 'WC2N 5NJ', 'suburb': 'Covent Garden', 'quarter': 'Westminster', 'street': 'Strand', 'housenumber': '1', 'iso3166_2': 'GB-ENG', 'iso3166_2_sublevel': 'GB-WSM', 'lon': -0.1265174, 'lat': 51.5078159, 'state_code': 'ENG', 'formatted': 'The Grand Caffè, 1 Strand, London, WC2N 5NJ, United Kingdom', 'address_line1': 'The Grand Caffè', 'address_line2': '1 Strand, London, WC2N 5NJ, United Kingdom', 'categories': ['catering', 'catering.cafe'], 'details': ['details.catering', 'details.facilities'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'lat': 51.5078159, 'lon': -0.1265174, 'city': 'London', 'name': 'The Grand Caffè', 'osm_id': 3098608835, 'street': 'Strand', 'amenity': 'cafe', 'country': 'GB', 'osm_type': 'n', 'check_date': '2025-08-20', 'housenumber': 1, 'indoor_seating': 'yes', 'outdoor_seating': 'yes'}}, 'facilities': {'outdoor_seating': True}, 'distance': 102, 'place_id': '5160feafdfb831c0bf59c471851c00c14940f00103f901c304b1b800000000920310546865204772616e642043616666c3a8'}, 'geometry': {'type': 'Point', 'coordinates': [-0.1265174, 51.5078159]}}, {'type': 'Feature', 'properties': {'name': 'Costa', 'country': 'United Kingdom', 'country_code': 'gb', 'state': 'England', 'city': 'City of Westminster', 'postcode': 'WC2N 5NG', 'suburb': 'Covent Garden', 'quarter': 'Westminster', 'street': 'Hungerford Lane', 'iso3166_2': 'GB-ENG', 'iso3166_2_sublevel': 'GB-WSM', 'lon': -0.1252987, 'lat': 51.5080331, 'state_code': 'ENG', 'formatted': 'Costa, Hungerford Lane, London, WC2N 5NG, United Kingdom', 'address_line1': 'Costa', 'address_line2': 'Hungerford Lane, London, WC2N 5NG, United Kingdom', 'categories': ['catering', 'catering.cafe', 'catering.cafe.coffee', 'catering.cafe.coffee_shop', 'vegan', 'vegetarian', 'wheelchair', 'wheelchair.yes'], 'details': ['details', 'details.catering', 'details.facilities', 'details.payment'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'lat': 51.5080331, 'lon': -0.1252987, 'name': 'Costa', 'brand': 'Costa', 'level': 0, 'osm_id': 573320919, 'amenity': 'cafe', 'cuisine': 'coffee_shop', 'name:en': 'Costa', 'smoking': 'no', 'toilets': 'no', 'osm_type': 'n', 'takeaway': 'yes', 'check_date': '2024-09-18', 'diet:vegan': 'yes', 'wheelchair': 'yes', 'drive_through': 'no', 'brand:wikidata': 'Q608845', 'brand:wikipedia': 'en:Costa Coffee', 'diet:vegetarian': 'yes', 'outdoor_seating': 'yes', 'payment:american_express': 'yes'}}, 'brand': 'Costa', 'brand_details': {'wikidata': 'Q608845', 'wikipedia': 'en:Costa Coffee'}, 'name_international': {'en': 'Costa'}, 'facilities': {'wheelchair': True, 'smoking': False, 'toilets': False, 'outdoor_seating': True, 'takeaway': True}, 'payment_options': {'american_express': True}, 'catering': {'cuisine': 'coffee_shop', 'diet': {'vegan': True, 'vegetarian': True}}, 'distance': 185, 'place_id': '51bd9b5dadc909c0bf598be4863a07c14940f00103f901d72e2c2200000000920305436f737461'}, 'geometry': {'type': 'Point', 'coordinates': [-0.1252987, 51.5080331]}}, {'type': 'Feature', 'properties': {'name': "Muriel's Kitchen", 'country': 'United Kingdom', 'country_code': 'gb', 'state': 'England', 'city': 'City of Westminster', 'postcode': 'WC2N 5DN', 'suburb': 'Covent Garden', 'quarter': 'Westminster', 'street': "St Martin's Place", 'iso3166_2': 'GB-ENG', 'iso3166_2_sublevel': 'GB-WSM', 'lon': -0.1274819, 'lat': 51.5089202, 'state_code': 'ENG', 'formatted': "Muriel's Kitchen, St Martin's Place, London, WC2N 5DN, United Kingdom", 'address_line1': "Muriel's Kitchen", 'address_line2': "St Martin's Place, London, WC2N 5DN, United Kingdom", 'categories': ['catering', 'catering.cafe', 'wheelchair', 'wheelchair.yes'], 'details': ['details', 'details.catering', 'details.facilities'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'lat': 51.5089202, 'lon': -0.1274819, 'city': 'London', 'name': "Muriel's Kitchen", 'osm_id': 3609864448, 'amenity': 'cafe', 'fhrs:id': 1470371, 'name:en': "Muriel's Kitchen", 'osm_type': 'n', 'postcode': 'WC2N 5DN', 'check_date': '2024-09-04', 'wheelchair': 'yes', 'addr:housename': 'The National Gallery', 'indoor_seating': 'yes', 'outdoor_seating': 'no'}}, 'name_international': {'en': "Muriel's Kitchen"}, 'facilities': {'wheelchair': True, 'outdoor_seating': False}, 'distance': 192, 'place_id': '51177daaaf5351c0bf590ba30f4c24c14940f00103f90100292ad7000000009203104d757269656c2773204b69746368656e'}, 'geometry': {'type': 'Point', 'coordinates': [-0.1274819, 51.5089202]}}, {'type': 'Feature', 'properties': {'name': 'Cafe in the Crypt', 'country': 'United Kingdom', 'country_code': 'gb', 'state': 'England', 'city': 'City of Westminster', 'postcode': 'WC2N 4JH', 'suburb': 'Covent Garden', 'quarter': 'Westminster', 'street': "St Martin's Place", 'housenumber': '5', 'iso3166_2': 'GB-ENG', 'iso3166_2_sublevel': 'GB-WSM', 'lon': -0.1266429, 'lat': 51.5089219, 'state_code': 'ENG', 'formatted': "Cafe in the Crypt, 5 St Martin's Place, London, WC2N 4JH, United Kingdom", 'address_line1': 'Cafe in the Crypt', 'address_line2': "5 St Martin's Place, London, WC2N 4JH, United Kingdom", 'categories': ['catering', 'catering.cafe', 'vegan', 'vegetarian', 'wheelchair', 'wheelchair.yes'], 'details': ['details', 'details.catering', 'details.facilities', 'details.payment'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'lat': 51.5089219, 'lon': -0.1266429, 'city': 'London', 'name': 'Cafe in the Crypt', 'layer': -1, 'osm_id': 11982082826, 'street': "St Martin's Place", 'amenity': 'cafe', 'country': 'GB', 'smoking': 'no', 'website': 'https://www.stmartin-in-the-fields.org/cafe-in-the-crypt/', 'osm_type': 'n', 'postcode': 'WC2N 4JH', '_inherited': '', 'check_date': '2024-09-02', 'diet:vegan': 'yes', 'wheelchair': 'yes', 'housenumber': 5, 'diet:vegetarian': 'yes', 'payment:american_express': 'yes'}}, 'website': 'https://www.stmartin-in-the-fields.org/cafe-in-the-crypt/', 'facilities': {'wheelchair': True, 'smoking': False}, 'payment_options': {'american_express': True}, 'catering': {'diet': {'vegan': True, 'vegetarian': True}}, 'distance': 203, 'place_id': '51f8a2e2a4d535c0bf59ed5b525a24c14940f00103f9010a1330ca020000009203114361666520696e20746865204372797074'}, 'geometry': {'type': 'Point', 'coordinates': [-0.1266429, 51.5089219]}}, {'type': 'Feature', 'properties': {'name': 'National Portrait Gallery Cafe', 'country': 'United Kingdom', 'country_code': 'gb', 'state': 'England', 'city': 'City of Westminster', 'postcode': 'WC2N 4JL', 'suburb': 'Covent Garden', 'quarter': 'Westminster', 'street': "St Martin's Place", 'iso3166_2': 'GB-ENG', 'iso3166_2_sublevel': 'GB-WSM', 'lon': -0.127509, 'lat': 51.5091122, 'state_code': 'ENG', 'formatted': "National Portrait Gallery Cafe, St Martin's Place, London, WC2N 4JL, United Kingdom", 'address_line1': 'National Portrait Gallery Cafe', 'address_line2': "St Martin's Place, London, WC2N 4JL, United Kingdom", 'categories': ['catering', 'catering.cafe', 'wheelchair', 'wheelchair.yes'], 'details': ['details.catering', 'details.facilities'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'lat': 51.5091122, 'lon': -0.127509, 'name': 'National Portrait Gallery Cafe', 'osm_id': 3609864449, 'amenity': 'cafe', 'osm_type': 'n', 'wheelchair': 'yes', 'indoor_seating': 'yes', 'outdoor_seating': 'no'}}, 'facilities': {'wheelchair': True, 'outdoor_seating': False}, 'distance': 213, 'place_id': '51850b79043752c0bf594f7fac962ac14940f00103f90101292ad70000000092031e4e6174696f6e616c20506f7274726169742047616c6c6572792043616665'}, 'geometry': {'type': 'Point', 'coordinates': [-0.127509, 51.5091122]}}, {'type': 'Feature', 'properties': {'name': 'Espresso Bar', 'country': 'United Kingdom', 'country_code': 'gb', 'state': 'England', 'city': 'City of Westminster', 'postcode': 'WC2H 7HS', 'district': "St. James's", 'suburb': 'Covent Garden', 'quarter': 'East Marylebone', 'street': 'Orange Street', 'iso3166_2': 'GB-ENG', 'iso3166_2_sublevel': 'GB-WSM', 'lon': -0.128771, 'lat': 51.5089976, 'state_code': 'ENG', 'formatted': 'Espresso Bar, Orange Street, London, WC2H 7HS, United Kingdom', 'address_line1': 'Espresso Bar', 'address_line2': 'Orange Street, London, WC2H 7HS, United Kingdom', 'categories': ['catering', 'catering.cafe', 'wheelchair', 'wheelchair.yes'], 'details': ['details', 'details.catering', 'details.facilities'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'lat': 51.5089976, 'lon': -0.128771, 'name': 'Espresso Bar', 'level': 0, 'osm_id': 10699089655, 'amenity': 'cafe', 'cuisine': 'coffeeshop', 'smoking': 'no', 'toilets': 'no', 'operator': 'National Gallery', 'osm_type': 'n', 'wheelchair': 'yes', 'outdoor_seating': 'no'}}, 'operator': 'National Gallery', 'facilities': {'wheelchair': True, 'smoking': False, 'toilets': False, 'outdoor_seating': False}, 'catering': {'cuisine': 'coffeeshop'}, 'distance': 216, 'place_id': '51f12bd670917bc0bf590adf56d526c14940f00103f901f726b77d0200000092030c457370726573736f20426172'}, 'geometry': {'type': 'Point', 'coordinates': [-0.128771, 51.5089976]}}, {'type': 'Feature', 'properties': {'name': 'Nero Express', 'country': 'United Kingdom', 'country_code': 'gb', 'state': 'England', 'city': 'City of Westminster', 'postcode': 'WC2N 6NA', 'suburb': 'Covent Garden', 'quarter': 'Westminster', 'street': 'Villiers Street', 'iso3166_2': 'GB-ENG', 'iso3166_2_sublevel': 'GB-WSM', 'lon': -0.1248521, 'lat': 51.5082124, 'state_code': 'ENG', 'formatted': 'Nero Express, Villiers Street, London, WC2N 6NA, United Kingdom', 'address_line1': 'Nero Express', 'address_line2': 'Villiers Street, London, WC2N 6NA, United Kingdom', 'categories': ['catering', 'catering.cafe', 'catering.cafe.coffee', 'catering.cafe.coffee_shop', 'vegetarian'], 'details': ['details', 'details.catering', 'details.contact', 'details.facilities', 'details.payment'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'lat': 51.5082124, 'lon': -0.1248521, 'name': 'Nero Express', 'brand': 'Caffè Nero', 'level': 0, 'osm_id': 4329962743, 'amenity': 'cafe', 'cuisine': 'coffee_shop', 'name:en': 'Nero Express', 'website': 'https://www.caffenero.com/uk/stores/charing-cross', 'osm_type': 'n', 'takeaway': 'only', 'check_date': '2026-06-21', 'wheelchair': 'no', 'payment:cash': 'yes', 'contact:phone': '+44 20 3272 0055', 'opening_hours': 'Mo-Fr 06:00-23:00; Sa 06:30-23:00; Su 07:00-22:00', 'brand:wikidata': 'Q675808', 'indoor_seating': 'no', 'brand:wikipedia': 'en:Caffè Nero', 'diet:vegetarian': 'yes', 'outdoor_seating': 'no', 'air_conditioning': 'yes', 'payment:debit_cards': 'yes', 'payment:credit_cards': 'yes', 'check_date:opening_hours': '2024-08-22'}}, 'website': 'https://www.caffenero.com/uk/stores/charing-cross', 'opening_hours': 'Mo-Fr 06:00-23:00; Sa 06:30-23:00; Su 07:00-22:00', 'brand': 'Caffè Nero', 'brand_details': {'wikidata': 'Q675808', 'wikipedia': 'en:Caffè Nero'}, 'name_international': {'en': 'Nero Express'}, 'contact': {'phone': '+44 20 3272 0055'}, 'facilities': {'wheelchair': False, 'air_conditioning': True, 'outdoor_seating': False, 'takeaway': True}, 'payment_options': {'cash': True, 'debit_cards': True, 'credit_cards': True}, 'catering': {'cuisine': 'coffee_shop', 'diet': {'vegetarian': True}}, 'distance': 222, 'place_id': '517e4056a64ef6bfbf59f9b59a1a0dc14940f00103f901f7fc15020100000092030c4e65726f2045787072657373'}, 'geometry': {'type': 'Point', 'coordinates': [-0.1248521, 51.5082124]}}, {'type': 'Feature', 'properties': {'name': 'Social Bite', 'country': 'United Kingdom', 'country_code': 'gb', 'state': 'England', 'city': 'City of Westminster', 'postcode': 'WC2R 0QU', 'district': 'St Clement Danes', 'suburb': 'Covent Garden', 'quarter': 'Westminster', 'street': 'Strand', 'housenumber': '448', 'iso3166_2': 'GB-ENG', 'iso3166_2_sublevel': 'GB-WSM', 'lon': -0.1254965, 'lat': 51.5087508, 'state_code': 'ENG', 'formatted': 'Social Bite, 448 Strand, London, WC2R 0QU, United Kingdom', 'address_line1': 'Social Bite', 'address_line2': '448 Strand, London, WC2R 0QU, United Kingdom', 'categories': ['catering', 'catering.cafe'], 'details': ['details.facilities', 'details.payment'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'lat': 51.5087508, 'lon': -0.1254965, 'city': 'London', 'name': 'Social Bite', 'level': 0, 'osm_id': 653124873, 'street': 'Strand', 'suburb': 'Strand', 'amenity': 'cafe', 'fhrs:id': 1902004, 'osm_

### Save the fields that we actually need

In [ ]:
columns2 = [
    "properties.place_id",
    "properties.name",
    "properties.categories",
    "properties.formatted",
    "properties.postcode",
    "properties.city",
    "properties.lat",
    "properties.lon",
    "properties.website",
    "properties.opening_hours"
]

df = df.reindex(columns=columns2) # Makes the dataframes columns match the order and names in the columns2 list

### Rename the columns to match the database fields:

In [ ]:
df = df.rename(columns={
    "properties.place_id": "geoapify_place_id",
    "properties.name": "name",
    "properties.categories": "categories",
    "properties.formatted": "address",
    "properties.postcode": "postcode",
    "properties.city": "city",
    "properties.lat": "latitude",
    "properties.lon": "longitude",
    "properties.website": "website",
    "properties.opening_hours": "opening_hours"
})

### Clean the category field to match the database

- Database schema only has one category field wheras API returns multiple.

In [13]:
def get_category(categories):
    if not isinstance(categories, list):
        return None

    wanted_prefixes = [
        "catering.cafe",
        "catering.restaurant",
        "entertainment.museum",
        "leisure.playground"
    ]

    for prefix in wanted_prefixes:
        for category in categories:
            if category.startswith(prefix):
                return category

    return None

df["category"] = df["categories"].apply(get_category)
df.sample(50)

,geoapify_place_id,name,categories,address,postcode,borough,latitude,longitude,website,opening_hours,category
247,513424383f0fffbcbf596aedc73725c34940f00103f901...,Mail Rail Museum,"[entertainment, entertainment.museum, fee, whe...","Mail Rail Museum, Phoenix Place, London, WC1X ...",WC1X 0BF,London Borough of Islington,51.524573,-0.113267,https://www.postalmuseum.org/,We-Su 10:00-17:00,entertainment.museum
256,51d2b30f689f7dc3bf59729307d8fdc24940f00103f901...,Royal Academy of Music Museum,"[entertainment, entertainment.museum]","Royal Academy of Music Museum, Marylebone Road...",NW1 5HT,NaN,51.523372,-0.152271,https://www.ram.ac.uk/museum,Fr 11:00-18:00,entertainment.museum
185,518ae76c01a1f5c0bf59cabf3b9e3bc14940f00103f901...,Tiger Tiger,"[catering, catering.restaurant]","Tiger Tiger, 29 Haymarket, London, SW1Y 4SP, U...",SW1Y 4SP,St. James's,51.509632,-0.132496,https://london.tigertiger.co.uk/,NaN,catering.restaurant
199,516d24647b88a1c0bf5952b5824b6cc14940f00103f901...,Petit Bistro,"[catering, catering.restaurant]","Petit Bistro, 14 Leicester Square, London, WC2...",WC2H 7NG,St. James's,51.511117,-0.129930,NaN,NaN,catering.restaurant
265,5153848e12aaa8b6bf5969e1ef32a5c04940f00102f901...,Old Operating Theatre Museum,"[building, building.tourism, entertainment, en...","Old Operating Theatre Museum, 9a St. Thomas St...",SE1 9RY,London Borough of Southwark,51.505025,-0.088520,https://oldoperatingtheatre.com/,Mo-Su 10:30-17:00,entertainment.museum
18,519fc9fe791a30c0bf5913c0289c38c14940f00103f901...,Rosetta,"[catering, catering.cafe]","Rosetta, 38 William IV Street, London, WC2B 4D...",WC2B 4DD,NaN,51.509540,-0.126468,https://www.facebook.com/rosettafarmlondon,Mo-Sa 10:30-19:30,catering.cafe
116,5165ecc4001dc9bfbf595654a35812c14940f00102f901...,Hobson Fish & Chips,"[catering, catering.restaurant]","Hobson Fish & Chips, 13-15 Villiers Street, Lo...",WC2N 6ND,NaN,51.508372,-0.124162,NaN,NaN,catering.restaurant
164,51447cbac0b568c0bf5990f30e0861c14940f00102f901...,Street Burger,"[catering, catering.restaurant, catering.resta...","Street Burger, 24 Charing Cross Road, London, ...",WC2H 0HX,NaN,51.510779,-0.128197,https://www.gordonramsayrestaurants.com/en/uk/...,Mo-Su 11:30-22:00; Th-Sa 11:30-23:00,catering.restaurant
213,517534754923bcbcbf594f2f3e067ec14940f00102f901...,Two Temple Place,"[building, building.tourism, entertainment, en...","Two Temple Place, 2 Temple Place, London, WC2R...",WC2R 3BD,St Clement Danes,51.511644,-0.112200,https://twotempleplace.org/,NaN,entertainment.museum
27,510c5634eb3439c0bf592e53b0c447c14940f00102f901...,Caffè Nero,"[building, building.catering, catering, cateri...","Caffè Nero, 36A St Martin's Lane, London, WC2N...",WC2N 4ER,NaN,51.510005,-0.126744,https://www.caffenero.com/uk/stores/st-martins...,Mo-Fr 07:00-20:30; Sa 07:30-20:30; Su 08:00-19:00,catering.cafe
257,51009013268c66c0bf599f82b2dfc9c34940f00103f901...,British Library Exhibition Space,"[entertainment, entertainment.museum, fee]","British Library Exhibition Space, 96 Euston Ro...",NW1 2SX,London Borough of Camden,51.529598,-0.128130,https://www.bl.uk/,"Jan-Dec: Mo, We-Fr 10:00-18:00; Jan-Dec: Tu 10...",entertainment.museum
11,5115dd1f949cb8c0bf594824c09fd0c04940f00103f901...,ICA Café Bar,"[catering, catering.cafe]","ICA Café Bar, The Mall, London, SW1Y 5AH, Unit...",SW1Y 5AH,St. James's,51.506367,-0.130634,https://www.ica.art/,NaN,catering.cafe
287,51323e456fca75b3bf59c85001ae19c14940f00102f901...,Waterloo Block,"[building, building.tourism, entertainment, en...","Waterloo Block, Inner Ward, London, EC3N 4DR, ...",EC3N 4DR,London Borough of Tower Hamlets,51.508602,-0.076022,NaN,NaN,entertainment.museum
15,516d510bcad9e0bfbf59edabbc2e0dc14940f00103f901...,The Pasty Shop,"[catering, catering.cafe, vegan, vegetarian, w...","The Pasty Shop, Villiers Street, London, WC2N ...",WC2N 5HS,NaN,51.508215,-0.124525,NaN,NaN,catering.cafe
160,512a8018d7aebfbfbf599a722abe46c14940f00103f901...,Plaza Khao Gaeng Covent Garden,"[catering, catering.restaurant, catering.resta...","Plaza Khao Gaeng Covent Garden, 6 Bedford Stre...",WC2E 9HA,St Clement Danes,51.509971,-0.124019,NaN,NaN,catering.restaurant
272,51843ccca843b8bfbf599e899fb591c44940f00103f901...,Queer Britain,"[entertainment, entertainment.museum, no_fee, ...","Queer Britain, 2 Granary Square, London, N1C 4...",N1C 4BH,London Borough of Camden,51.535697,-0.123905,https://queerbritain.org.uk/,Mo-Tu off; We-Su 12:00-18:00,entertainment.museum
268,51c2d4e0c7e248c4bf59d72da7a90ac34940f00103f901...,Sherlock Holmes Museum,"[entertainment, entertainment.museum, fee]","Sherlock Holmes Museum, 221B Baker Street, Lon...",NW1 6XE,NaN,51.523763,-0.158474,https://www.sherlock-holmes.co.uk/,Mo-Su 09:30-18:00,entertainment.museum
274,510168b57b97cfb4bf595df5963fd7c04940f00102f901...,HMS Belfast,"[building, building.historic, building.tourism...","HMS Belfast, The Queen's Walk, London, SE1 2JH...",SE1 2JH,London Borough of Southwark,51.506543,-0.081152,https://www.iwm.org.uk/visits/hms-belfast,Mo-Su 10:00-17:00; Dec 24-26 off,entertainment.museum
191,517e9065c1c41fc1bf59eccd5e6c10c14940f00103f901...,Shoryu,"[catering, catering.restaurant, catering.resta...","Shoryu, 8 Regent Street St James's, London, SW...",SW1Y 4LR,St. James's,51.508314,-0.133782,https://shoryuramen.com/,Mo-Th 11:30-22:30; Fr-Sa 11:30-23:00; Su 11:30...,catering.restaurant
149,5135e5af3500c0c0bf59685da3e540c14940f00103f901...,Whitcombs,"[catering, catering.restaurant, catering.resta...","Whitcombs, 38 Leicester Square, London, WC2H 7...",WC2H 7DX,St. James's,51.509793,-0.130859,https://www.thelondoner.com/restaurants-bars/w...,NaN,catering.restaurant
177,51d5c3e1163d01c1bf5955f42cad2bc14940f00103f901...,Anzu,"[catering, catering.restaurant]","Anzu, Norris Street, London, SW1Y 4QX, United ...",SW1Y 4QX,St. James's,51.509145,-0.132850,NaN,NaN,catering.restaurant
270,516d97ec8e7ba9b6bf59e769656776c24940f00103f901...,British Red Cross Museum,"[entertainment, entertainment.museum, no_fee, ...","British Red Cross Museum, 44 Moorfields, City ...",EC2Y 9AL,Broadgate,51.519238,-0.088524,https://www.redcross.org.uk/about-us/our-histo...,Mo-Fr 09:00-18:00,entertainment.museum
211,51e1e93af9991fbebf59dce1653c00c04940f00103f901...,The Florence Nightingale Museum,"[entertainment, entertainment.museum, fee, whe...","The Florence Nightingale Museum, 2 Lambeth Pal...",SE1 7EP,London Borough of Lambeth,51.500007,-0.117670,https://www.florence-nightingale.co.uk/,"Tu-Su 10:00-17:00; ""Last Th of month close at ...",entertainment.museum
276,51fd481e983184c4bf596b3f609f3dbe4940f00102f901...,National Army Museum,"[building, building.tourism, entertainment, en...","National Army Museum, Royal Hospital Road, Lon...",SW3 4HT,Royal Borough of Kensington and Chelsea,51.486258,-0.160287,https://www.nam.ac.uk/,NaN,entertainment.museum
128,514245f7e0eea4bfbf59b5ec6bc109c14940f00102f901...,Ippudo,"[building, building.catering, catering, cateri...","Ippudo, 31 Villiers Street, London, WC2N 6ND, ...",WC2N 6ND,NaN,51.508110,-0.123611,NaN,Su-Tu 12:00-20:30; We-Sa 12:00-21:00,catering.restaurant
201,51bc96e829e9f8bfbf59b1a7d2b2fac04940f00102f901...,Benjamin Franklin House,"[building, building.historic, building.tourism...","Benjamin Franklin House, 36 Craven Street, Lon...",WC2N 5NF,NaN,51.507669,-0.124867,https://benjaminfranklinhouse.org/,Fr-Su 12:00-17:00,entertainment.museum
2,510b0c59ddea39c0bf59111ac1c6f5c04940f00103f901...,Costa,"[catering, catering.cafe, catering.cafe.coffee...","Costa, 1 Strand, London, WC2N 5NJ, United Kingdom",WC2N 5NJ,NaN,51.507500,-0.126768,NaN,NaN,catering.cafe
249,517923204fcd34c3bf596f1f9f1cbfc24940f00102f901...,The Museum of Philatelic History,"[building, building.tourism, entertainment, en...","The Museum of Philatelic History, 41 Devonshir...",W1G 6JY,NaN,51.521470,-0.150022,http://www.rpsl.org.uk/museum.asp,Mo-Fr 09:30-16:30,entertainment.museum
392,51bae168d9934dbbbf59cabdf4ca43c34940f00102f901...,Three Corners Adventure Playground,"[leisure, leisure.playground]","Three Corners Adventure Playground, Skinner St...",EC1R 0LN,London Borough of Islington,51.525539,-0.106692,NaN,NaN,leisure.playground
162,514b6ebfdfea08c1bf590f4fde950dc14940f00102f901...,San Carlo,"[catering, catering.restaurant, catering.resta...","San Carlo, 2 Regent Street St James's, London,...",SW1Y 4LR,St. James's,51.508225,-0.133084,NaN,NaN,catering.restaurant
144,51de52735e08dec0bf59a711e96d22c14940f00103f901...,Americana,"[catering, catering.restaurant]","Americana, 11 Haymarket, London, SW1Y 4BP, Uni...",SW1Y 4BP,St. James's,51.508863,-0.131776,NaN,NaN,catering.restaurant
21,516e68ca4e3fa8bfbf5923bc3d0801c14940f00103f901...,Starbucks,"[catering, catering.cafe, catering.cafe.coffee...","Starbucks, 14 Villiers Street, London, WC2N 6R...",WC2N 6RH,NaN,51.507844,-0.123661,https://www.starbucks.co.uk/,NaN,catering.cafe
88,51b6717acd61adc0bf59b7d7dd978ec14940f00103f901...,Chatime,"[catering, catering.cafe, catering.cafe.bubble...","Chatime, 4 Gerrard Street, London, W1D 5AP, Un...",W1D 5AP,NaN,51.512164,-0.130291,https://www.chatimeuk.com/,Mo-Su 12:00-20:00; Sa 11:00-23:00,catering.cafe
192,51618fe44dd944bfbf592843fa9232c14940f00103f901...,Smith & Wollensky,"[catering, catering.restaurant]","Smith & Wollensky, 1 - 11 John Adam Street, Lo...",WC2N 6HT,St Clement Danes,51.509356,-0.122144,NaN,NaN,catering.restaurant
52,5169e55e605628c0bf597ba4c16d6dc14940f00103f901...,Qima Cafe Covent Garden,"[catering, catering.cafe, internet_access]","Qima Cafe Covent Garden, 21-22 New Row, London...",WC2N 4LE,NaN,51.511152,-0.126231,https://qimacafe.com/,Mo-Fr 08:00-19:00; Sa 09:00-19:00; Su 09:00-17:00,catering.cafe
58,512b60b4ff667cc0bf598dfa366974c14940f00102f901...,Crêpeaffaire,"[catering, catering.cafe]","Crêpeaffaire, Cranbourn Street, London, WC2H 7...",WC2H 7JH,St. James's,51.511365,-0.128797,https://www.crepeaffaire.com/locations/united-...,Mo-Su 11:00-20:00,catering.cafe
260,5193f6aba525fbc4bf59be912f57f5bf4940f00103f901...,Paradox Museum,"[entertainment, entertainment.museum, fee, whe...","Paradox Museum, 90 Brompton Road, London, SW3 ...",SW3 1JJ,NaN,51.499675,-0.163914,https://paradoxmuseum.com/london/,Mo-Th 10:00-17:30; Fr 10:00-19:00; Sa 09:30-19...,entertainment.museum
16,51853c2762b609c0bf5900e7204322c14940f00103f901...,Coffee & Real eating co.,"[catering, catering.cafe]","Coffee & Real eating co., 442 Strand, London, ...",WC2R 0QU,St Clement Danes,51.508858,-0.125296,NaN,NaN,catering.cafe
292,51cf82d8578b89b4bf59ca174f5aebc24940f00102f901...,Museum of Shakespeare,"[building, building.tourism, entertainment, en...","Museum of Shakespeare, 20 Curtain Road, London...",EC2A 3NY,London Borough of Hackney,51.522795,-0.080218,https://www.museumofshakespeare.org.uk/,NaN,entertainment.museum
7,51850b79043752c0bf594f7fac962ac14940f00103f901...,National Portrait Gallery Cafe,"[catering, catering.cafe, wheelchair, wheelcha...","National Portrait Gallery Cafe, St Martin's Pl...",WC2N 4JL,NaN,51.509112,-0.127509,NaN,NaN,catering.cafe
5,51177daaaf5351c0bf590ba30f4c24c14940f00103f901...,Muriel's Kitchen,"[catering, catering.cafe, wheelchair, wheelcha...","Muriel's Kitchen, St Martin's Place, London, W...",WC2N 5DN,NaN,51.508920,-0.127482,NaN,NaN,catering.cafe
38,51861e317a6ea1bfbf5987dee2e13dc14940f00103f901...,Black Sheep Coffee,"[catering, catering.cafe, catering.cafe.coffee...","Black Sheep Coffee, 425 Strand, London, WC2R 0...",WC2R 0QE,St Clement Danes,51.509701,-0.123557,https://blacksheepcoffee.co.uk/blogs/locations...,NaN,catering.cafe
221,51413dc791184ec2bf59c90b9f63f6c14940f00103f901...,Twist Museum,"[entertainment, entertainment.museum]","Twist Museum, 248 Oxford Street, London, W1C 2...",W1C 2DQ,NaN,51.515332,-0.143008,https://twistmuseum.com,Mo-Th 11:00-19:30; Fr 11:00-21:00; Sa 10:00-21...,entertainment.museum
108,5109ff2268cc24c0bf598b8ba37213c14940f00103f901...,PizzaExpress,"[catering, catering.restaurant, catering.resta...","PizzaExpress, 450 Strand, London, WC2R 0RG, Un...",WC2R 0RG,NaN,51.508406,-0.126123,https://www.pizzaexpress.com/london-450-strand,Mo-We 11:30-22:30; Th-Sa 11:30-23:00; Su 11:30...,catering.restaurant
183,51a1ec7772970ec1bf59e976402322c14940f00103f901...,Sael,"[catering, catering.restaurant]","Sael, Carlton Street, London, SW1Y 4QQ, United...",SW1Y 4QQ,St. James's,51.508854,-0.133258,NaN,NaN,catering.restaurant
80,512321808a9933bfbf5994d519845ec14940f00103f901...,Costa,"[catering, catering.cafe, catering.cafe.coffee...","Costa, 37 Southampton Street, London, WC2E 7HG...",WC2E 7HG,St Clement Danes,51.510697,-0.121881,NaN,Mo-Sa 06:30-20:00; Su 07:00-18:30,catering.cafe
284,51cceb88433690c6bf59e9a7ee80a1bf4940f00103f901...,The Clockmakers' Museum,"[entertainment, entertainment.museum, no_fee, ...","The Clockmakers' Museum, Exhibition Road, Lond...",SW7 2DD,Royal Borough of Kensington and Chelsea,51.497116,-0.176276,http://www.clockmakers.org/the-clockmakers-mus...,Mo-Su 10:00-18:00,entertainment.museum
135,51e05ba2c4f87ac0bf5964fd0ba947c14940f00103f901...,Vespa,"[catering, catering.restaurant, catering.resta...","Vespa, 9A Irving Street, London, WC2H 7AT, Uni...",WC2H 7AT,NaN,51.509999,-0.128753,NaN,NaN,catering.restaurant
46,51ba49b148b835c0bf5936c2ecaf68c14940f00103f901...,Knoops,"[catering, catering.cafe]","Knoops, 2a New Row, London, WC2N 4LA, United K...",WC2N 4LA,NaN,51.511007,-0.126639,https://knoops.co.uk/,NaN,catering.cafe
259,5165e7f54089d7c3bf598cb19463eec24940f00102f901...,Madame Tussauds,"[building, building.tourism, entertainment, en...","Madame Tussauds, 8-10 Marylebone Road, London,...",NW1 5LR,NaN,51.522923,-0.154852,https://www.madametussauds.com/london/en/plan-...,Mo-Fr 09:30-17:30; Sa-Su 09:00-18:00,entertainment.museum

### Removal of null values
- The below code shows the venues that have null values and the cell block after that removes these values.

In [9]:
df[df['latitude'].isnull() | df['longitude'].isnull() | df['name'].isnull() | df['geoapify_place_id'].isnull()]

,geoapify_place_id,name,categories,address,postcode,borough,latitude,longitude,website,opening_hours,category
157,512d4c658a700cc1bf597f446cd3f8c04940f00102f901...,NaN,"[catering, catering.restaurant]","12 Waterloo Place, London, SW1Y 4AR, United Ki...",SW1Y 4AR,St. James's,51.507594,-0.133192,NaN,NaN,catering.restaurant
300,51175b54f4e196bebf59c9dfda4c38c14940f00102f901...,NaN,"[access, access.yes, leisure, leisure.playgrou...","Victoria Embankment, London, WC2N 6PB, United ...",WC2N 6PB,St Clement Danes,51.509489,-0.119522,NaN,NaN,leisure.playground
302,5168cf09f87f74c0bf5915645a1ee7c14940f00102f901...,NaN,"[access, access.yes, leisure, leisure.playground]","St. Giles Passage, London, WC2H 8DE, United Ki...",WC2H 8DE,London Borough of Camden,51.514884,-0.128565,NaN,NaN,leisure.playground
304,5115ff412497cabebf59dd9d0053d0c14940f00102f901...,NaN,"[leisure, leisure.playground]","Drury Lane, London, WC2B 5SQ, United Kingdom",WC2B 5SQ,St Clement Danes,51.514170,-0.120279,NaN,NaN,leisure.playground
305,515806646c79b6c1bf59e6cda02124c04940f00102f901...,NaN,"[access, access.yes, leisure, leisure.playground]","Birdcage Walk, London, SW1H 9AP, United Kingdom",SW1H 9AP,NaN,51.501100,-0.138368,NaN,NaN,leisure.playground
...,...,...,...,...,...,...,...,...,...,...,...
395,514411d9ac9fa3b9bf59c217265305bf4940f00102f901...,NaN,"[leisure, leisure.playground]","Hampton Street, London, SE1 6SL, United Kingdom",SE1 6SL,London Borough of Southwark,51.492350,-0.100153,NaN,NaN,leisure.playground
396,51b28a2a01f96cbbbf5923e1f0d153c34940f00102f901...,NaN,"[leisure, leisure.playground]","Northampton Road, London, EC1R 0HU, United Kin...",EC1R 0HU,London Borough of Islington,51.526011,-0.107122,NaN,NaN,leisure.playground
397,51d73638d5f2bcb8bf59a4fc65017bc24940f00102f901...,NaN,"[access_limited, access_limited.private, leisu...","Thomas More Highwalk, City of London, EC2Y 8BT...",EC2Y 8BT,NaN,51.519379,-0.096633,NaN,NaN,leisure.playground
398,5197497b24d37ac2bf59a1f5251852be4940f00102f901...,NaN,"[leisure, leisure.playground]","Lupus Street, London, SW1V 3HD, United Kingdom",SW1V 3HD,NaN,51.486935,-0.144378,NaN,NaN,leisure.playground
399,51f4e8d83c2ccec1bf592fc8973a1fbe4940f00102f901...,NaN,"[leisure, leisure.playground]","Grosvenor Road, London, SW1V 3JD, United Kingdom",SW1V 3JD,Tachbrook Estate,51.485328,-0.139104,NaN,NaN,leisure.playground

In [10]:
df = df.dropna(subset=[
    'latitude',
    'longitude',
    'name',
    'geoapify_place_id',
    'postcode'
])

- Now the same code that checks for null values returns no results.

In [11]:
df[df['latitude'].isnull() | df['longitude'].isnull() | df['name'].isnull() | df['geoapify_place_id'].isnull()]

Empty DataFrame
Columns: [geoapify_place_id, name, categories, address, postcode, borough, latitude, longitude, website, opening_hours, category]
Index: []

- No duplicated valeus:

In [12]:
df[df.duplicated(keep=False)]

TypeError: unhashable type: 'list'

### Clean venue names
- Remove white spaces in front or trailing

In [ ]:
df["name"] = df["name"].str.strip()

### Clean postcodes

In [ ]:
df["postcode"] = (
    df["postcode"].str.strip().str.upper()
)

In [ ]:
print(df.info())
print(df.shape)
print(len(df))

<class 'pandas.DataFrame'>
Index: 318 entries, 0 to 394
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   geoapify_place_id  318 non-null    str
 1   name               318 non-null    str
 2   address            318 non-null    str
 3   postcode           318 non-null    string
 4   borough            197 non-null    str
 5   latitude           318 non-null    float64
 6   longitude          318 non-null    float64
 7   website            179 non-null    str
 8   opening_hours      112 non-null    str
 9   category           318 non-null    str
dtypes: float64(2), str(7), string(1)
memory usage: 27.3 KB
None
(318, 10)
318

### Export cleaned data to the cleaned data folder:

In [ ]:
df.to_json(
    CLEAN_JSON,
    orient="records",
    indent=2,
    force_ascii=False
)

df.to_csv(
    CLEAN_CSV,
    index=False
)